### ISSUE TITLE
dest-dir option

### ISSUE THREAD

**Issue by blond** [blond/tartifacts#66]
**Example:**

Need create artifact with project sources and write tarball next to the project directory.

```
project/
    sources/
project.tar.gz
```

**Now** we should use `dest` param in artifact info:

``` js
const tartifacts = require('tartifacts');

const artifacts = [
    {
        dest: '../project.tar.gz',
        patterns: [
            'sources/**',
            '!sources/exlib/**'
        ],
        tar: true,
        gzip: { level: 1 }
    }
];

tartifacts(artifacts, { root: 'path/to/project' });
```

Because of this, you can't describe config with artifacts in project. And you can't configure dest path using config.

Need add `dest` option to `tartifacts` and `name` parameter in artifact info:

``` js
const tartifacts = require('tartifacts');

const artifacts = [
    {
        name: 'project.tar.gz',
        patterns: [
            'sources/**',
            '!sources/exlib/**'
        ],
        tar: true,
        gzip: { level: 1 }
    }
];

tartifacts(artifacts, {
    root: 'path/to/project',
    destDir: path.join('path/to/project', '..')
});
```

**Comment by anton-rudeshko** [comment]
It's better to name it `--dest-dir/destDir`. Maybe also `name` → `filename`

**Comment by blond** [comment]
> It's better to name it --dest-dir/destDir

Yep it's better, update description.

> Maybe also name → filename

No, artifact name can be is directory.
